import { Language } from './types'
import SnapLogo from '../assets/Snap.svg'
import publishOneNav from '../assets/publishone-nav.svg'
import publishOneChat from '../assets/publishone-chat.png'
import vjoonNav from '../assets/vjoon-nav.svg'
import vjoonChat from '../assets/vjoon-chat.png'
export const FILTER_FIELD = 'city'
export const FILTER_FIELD2 = 'streetAddress'

export const logos = {
  navbar: {
    default: SnapLogo,
    publishone: publishOneNav,
    vjoon: vjoonNav,
    'vjoon k4': vjoonNav
  },
  chat: {
    default: SnapLogo,
    publishone: publishOneChat,
    vjoon: vjoonChat,
    'vjoon k4': vjoonChat
  }
}

export const translations: Record<Language, Record<string, string>> = {
  en: {
    // Navbar
    'navbar.chatbot': 'Chatbot',
    'navbar.uploadFiles': 'Upload Files',
    'navbar.history': 'History',
    'navbar.systemMessage': 'System Message',
    'navbar.logout': 'Logout',

    // FileUpload
    'fileUpload.chooseFile': 'Please select files to upload',
    'fileUpload.pdfOnly': 'Please select only PDF files for this button',
    'fileUpload.xmlOnly': 'Please select only XML files for this button',
    'fileUpload.orgRequired': 'Organization name is required to upload files',
    'fileUpload.orgPrompt': 'Please enter the organization name for upload:',
    'fileUpload.processing': 'Processing...',
    'fileUpload.uploadPdfButton': 'Upload PDF',
    'fileUpload.uploadXmlButton': 'Upload XML',
    'fileUpload.deleteAllButton': 'Delete All',
    'fileUpload.filterLabel': 'Filter by organization:',
    'fileUpload.allOrganizations': 'All',
    'fileUpload.uploadedFiles': 'Uploaded Files',
    'fileUpload.noFiles': 'No files uploaded yet',
    'fileUpload.prevPage': 'Previous',
    'fileUpload.nextPage': 'Next',
    'fileUpload.pageInfo': 'Page {current} of {total}',
    'fileUpload.delete': 'Delete',
    'fileUpload.fetchFailed': 'Failed to fetch files',
    'fileUpload.pdfProcessing': 'Processing and splitting files may take a while...',
    'fileUpload.pdfSuccess': 'Files uploaded and processed successfully!',
    'fileUpload.xmlProcessing': 'Processing XML...',
    'fileUpload.xmlSuccess': 'XML files uploaded successfully!',
    'fileUpload.uploadError': 'An error occurred during upload',
    'fileUpload.deleteAllConfirm':
      'Do you really want to delete all files and documents? This action cannot be undone.',
    'fileUpload.deletingAll': 'Deleting files and documents...',
    'fileUpload.deleteAllSuccess': 'Files and documents deleted!',
    'fileUpload.deleteAllFailed': 'Failed to delete files and documents',
    'fileUpload.deleteError': 'Error deleting files and documents:',
    'fileUpload.unexpectedError': 'An unexpected error occurred while deleting files.',
    'fileUpload.deleteSingleConfirm': 'Do you really want to delete {filename} and all related documents?',
    'fileUpload.deletingSingle': 'Deleting {filename}...',
    'fileUpload.deleteSingleSuccess': 'File "{filename}" and related documents deleted!',
    'fileUpload.deleteSingleFailed': 'Could not delete "{filename}"',

    // Chat component translations
    'chat.title': 'Ask me a question!',
    'chat.subtitle': 'This chatbot can answer your questions',
    'chat.sessionExpired': 'Session expired, please login again.',
    'chat.defaultError':
      'An error occurred. Please try again. If the problem persists, please contact the site administrator.',
    'chat.historyError': "There was an error generating a response. Chat history can't be saved at this time. {error}",
    'chat.clearErrorTitle': 'Error clearing current chat',
    'chat.clearErrorSubtitle': 'Please try again. If the problem persists, please contact the site administrator.',
    'chat.contentFilterError':
      'The prompt was filtered due to triggering Azure OpenAI’s content filtering system.\nReason: This prompt contains content flagged as {reason}\n\nPlease modify your prompt and retry. Learn more: https://go.microsoft.com/fwlink/?linkid=2198766',
    'chat.saveError':
      "An error occurred. Answers can't be saved at this time. If the problem persists, please contact the site administrator.",
    'chat.historyDisabled': 'Chat history is not enabled',
    'chat.contactAdmin': 'Please contact the site administrator.',
    'chat.generatingAnswer': 'Generating answer...',
    'chat.stopGenerating': 'Stop generating',
    'chat.inputPlaceholder': 'Type a new question...',
    'chat.close': 'Close',
    'chat.error': 'Error',
    'chat.newChatButton': 'Start a new chat',
    'chat.clearChatButton': 'Clear chat',
    'chat.citationsPanel': 'Citations Panel',
    'chat.citations': 'Citations',
    'chat.closeCitationsPanel': 'Close citations panel',
    'chat.intentsPanel': 'Intents Panel',
    'chat.intents': 'Intents',
    'chat.closeIntentsPanel': 'Close intents panel',
    'chat.intent': 'Intent',
    'chat.searchQuery': 'Search Query',
    'chat.searchResult': 'Search Result',
    'chat.codeGenerated': 'Code Generated',

    // Auth messages
    'auth.notConfiguredTitle': 'Authentication Not Configured',
    'auth.notConfiguredSubtitle1':
      'This app does not have authentication configured. Please add an identity provider by finding your app in the',
    'auth.azurePortal': 'Azure Portal',
    'auth.notConfiguredSubtitle2': 'and following',
    'auth.instructions': 'these instructions',
    'auth.notConfiguredSubtitle3': '.',
    'auth.configNote1': 'Authentication configuration takes a few minutes to apply.',
    'auth.configNote2': 'If you deployed in the last 10 minutes, please wait and reload the page after 10 minutes.',

    'layout.logout': 'Logout',
    'layout.hideChatHistory': 'Hide chat history',
    'layout.showChatHistory': 'Show chat history',
    'layout.hideHistoryShort': 'Hide history',
    'layout.showHistoryShort': 'Show history',
    'layout.shareDialogTitle': 'Share the web app',
    'layout.copy': 'Copy',
    'layout.copied': 'Copied',

    // Answer component translations
    'answer.followupPrefix': 'Follow-up questions:',
    'answer.followupHeading': 'Follow-up questions',
    'answer.openReferences': 'Open references',
    'answer.multipleSources': '{count} sources',
    'answer.singleSource': '1 source',
    'answer.disclaimer': 'AI-generated content may be inaccurate',
    'answer.openIntents': 'Open intents',
    'answer.showIntents': 'Show Intents',

    // Feedback translations
    'feedback.likeLabel': 'Like this response',
    'feedback.dislikeLabel': 'Dislike this response',
    'feedback.sendFeedback': 'Send feedback',
    'feedback.helpImprove': 'Your feedback helps us improve answer quality',
    'feedback.submitNotice': 'Clicking "Submit" sends your feedback to the responsible team',
    'feedback.submit': 'Submit',
    'feedback.unhelpfulPrompt': 'Why was this response unhelpful?',
    'feedback.missingCitation': 'Missing citations',
    'feedback.wrongCitation': 'Incorrect citations',
    'feedback.outOfScope': 'Answer not based on my data',
    'feedback.inaccurateOrIrrelevant': 'Inaccurate or irrelevant',
    'feedback.otherUnhelpful': 'Other',
    'feedback.reportInappropriate': 'Report inappropriate content',
    'feedback.contentIs': 'The content is',
    'feedback.hateSpeech': 'Hate speech, stereotyping, demeaning',
    'feedback.violent': 'Violent: glorifying violence, self-harm',
    'feedback.sexual': 'Sexual: explicit content, grooming',
    'feedback.manipulative': 'Manipulative: deceitful, emotional, intrusive, tyrannical',
    'feedback.otherHarmful': 'Other',

    'chatHistory.recent': 'Recent',
    'chatHistory.empty': 'No chat history.',
    'chatHistory.deleteDialog.title': 'Do you really want to delete this item?',
    'chatHistory.deleteDialog.subText': 'The history of this chat session will be permanently deleted.',
    'chatHistory.renameError.sameTitle': 'Error: Enter a new title to proceed.',
    'chatHistory.renameError.general': 'Error: could not rename item',
    'chatHistory.itemAriaLabel': 'chat history item',
    'chatHistory.editFormAriaLabel': 'edit title form',
    'chatHistory.actionButtonsAriaLabel': 'action button group',
    'chatHistory.confirmEditAriaLabel': 'confirm new title',
    'chatHistory.cancelEditAriaLabel': 'cancel edit title',
    'chatHistory.deleteError': 'Error: could not delete item',
    'chatHistory.groupAriaLabel': 'chat history group',
    'chatHistory.listAriaLabel': 'chat history list',
    'chatHistory.loadingAriaLabel': 'loading more chat history',
    close: 'Close',
    delete: 'Delete',
    edit: 'Edit',
    cancel: 'Cancel',
    'chatHistory.panelAriaLabel': 'chat history panel',
    'chatHistory.headerAriaLabel': 'chat history header',
    'chatHistory.contentAriaLabel': 'chat history panel content',
    'chatHistory.title': 'Chat History',
    'chatHistory.clearAll': 'Clear all chat history',
    'chatHistory.clearAllDialog.title': 'Do you really want to clear all chat history?',
    'chatHistory.clearAllDialog.errorTitle': 'Error clearing all chat history',
    'chatHistory.clearAllDialog.subText': 'All chat history will be permanently deleted.',
    'chatHistory.clearAllDialog.errorSubText':
      'Please try again. If the problem persists, please contact the site administrator.',
    'chatHistory.clearAllButton': 'Clear all',
    'chatHistory.loadingError': 'Error loading chat history',
    'chatHistory.savingDisabled': "Chat history can't be saved at this time",
    'chatHistory.loading': 'Loading chat history',
    'chatHistory.loadingAriaLabel1': 'loading chat history',
    hide: 'Hide'
  },
  de: {
    // Navbar
    'navbar.chatbot': 'Chatbot',
    'navbar.uploadFiles': 'Dateien hochladen',
    'navbar.history': 'Verlauf',
    'navbar.systemMessage': 'Systemnachricht',
    'navbar.logout': 'Logout',

    // FileUpload
    'fileUpload.chooseFile': 'Bitte wählen Sie die hochzuladenden Dateien aus',
    'fileUpload.pdfOnly': 'Bitte wählen Sie nur PDF-Dateien für diesen Button aus',
    'fileUpload.xmlOnly': 'Bitte wählen Sie nur XML-Dateien für diesen Button aus',
    'fileUpload.orgRequired': 'Zum Hochladen von Dateien ist der Name der Organisation erforderlich',
    'fileUpload.orgPrompt': 'Bitte geben Sie für den Upload den Organisationsnamen ein:',
    'fileUpload.processing': 'Verarbeitung...',
    'fileUpload.uploadPdfButton': 'PDF hochladen',
    'fileUpload.uploadXmlButton': 'XML hochladen',
    'fileUpload.deleteAllButton': 'Alle löschen',
    'fileUpload.filterLabel': 'Filtern nach Organisation:',
    'fileUpload.allOrganizations': 'Alle',
    'fileUpload.uploadedFiles': 'Hochgeladene Dateien',
    'fileUpload.noFiles': 'Noch keine Dateien hochgeladen',
    'fileUpload.prevPage': 'Vorherige',
    'fileUpload.nextPage': 'Nächste',
    'fileUpload.pageInfo': 'Seite {current} von {total}',
    'fileUpload.delete': 'Löschen',
    'fileUpload.fetchFailed': 'Abrufen der Dateien fehlgeschlagen',
    'fileUpload.pdfProcessing': 'Das Verarbeiten und Aufteilen von Dateien kann eine Weile dauern...',
    'fileUpload.pdfSuccess': 'Dateien erfolgreich hochgeladen und verarbeitet!',
    'fileUpload.xmlProcessing': 'XML wird verarbeitet...',
    'fileUpload.xmlSuccess': 'XML-Dateien erfolgreich hochgeladen!',
    'fileUpload.uploadError': 'Beim Hochladen ist ein Fehler aufgetreten',
    'fileUpload.deleteAllConfirm':
      'Möchten Sie Dateien und Dokumente wirklich löschen? Diese Aktion kann nicht rückgängig gemacht werden.',
    'fileUpload.deletingAll': 'Dateien und Dokumente werden gelöscht...',
    'fileUpload.deleteAllSuccess': 'Dateien und Dokumente wurden gelöscht!',
    'fileUpload.deleteAllFailed': 'Das Löschen von Dateien und Dokumenten ist fehlgeschlagen',
    'fileUpload.deleteError': 'Fehler beim Löschen von Dateien und Dokumenten:',
    'fileUpload.unexpectedError': 'Beim Löschen von Dateien ist ein unerwarteter Fehler aufgetreten.',
    'fileUpload.deleteSingleConfirm': 'Möchten Sie {filename} und alle zugehörigen Dokumente wirklich löschen?',
    'fileUpload.deletingSingle': '{filename} wird gelöscht...',
    'fileUpload.deleteSingleSuccess': 'Datei „{filename}“ und zugehörige Dokumente wurden gelöscht!',
    'fileUpload.deleteSingleFailed': '„{filename}“ konnte nicht gelöscht werden',

    // Chat component translations
    'chat.title': 'Stell mir eine Frage!',
    'chat.subtitle': 'Dieser Chatbot kann deine Fragen beantworten',
    'chat.sessionExpired': 'Sitzung abgelaufen, bitte melden Sie sich erneut an.',
    'chat.defaultError':
      'Ein Fehler ist aufgetreten. Bitte versuchen Sie es erneut. Wenn das Problem weiterhin besteht, wenden Sie sich an den Administrator der Website.',
    'chat.historyError':
      'Bei der Generierung einer Antwort ist ein Fehler aufgetreten. Der Chatverlauf kann derzeit nicht gespeichert werden. {error}',
    'chat.clearErrorTitle': 'Fehler beim Löschen des aktuellen Chats',
    'chat.clearErrorSubtitle':
      'Bitte versuchen Sie es erneut. Wenn das Problem weiterhin besteht, wenden Sie sich an den Administrator der Website.',
    'chat.contentFilterError':
      'Die Eingabeaufforderung wurde aufgrund der Auslösung des Inhaltsfiltersystems von Azure OpenAI gefiltert.\nGrund: Diese Eingabeaufforderung enthält Inhalte, die als {reason} gekennzeichnet sind.\n\nBitte ändern Sie Ihre Eingabeaufforderung und versuchen Sie es erneut. Weitere Informationen: https://go.microsoft.com/fwlink/?linkid=2198766',
    'chat.saveError':
      'Ein Fehler ist aufgetreten. Antworten können derzeit nicht gespeichert werden. Wenn das Problem weiterhin besteht, wenden Sie sich an den Administrator der Website.',
    'chat.historyDisabled': 'Chatverlauf ist nicht aktiviert',
    'chat.contactAdmin': 'Bitte wenden Sie sich an den Administrator der Website.',
    'chat.generatingAnswer': 'Antwort wird generiert...',
    'chat.stopGenerating': 'Beantwortung abbrechen',
    'chat.inputPlaceholder': 'Neue Frage eingeben...',
    'chat.close': 'Schließen',
    'chat.error': 'Fehler',
    'chat.newChatButton': 'Neuen Chat starten',
    'chat.clearChatButton': 'Chat löschen',
    'chat.citationsPanel': 'Zitierpanel',
    'chat.citations': 'Zitate',
    'chat.closeCitationsPanel': 'Zitierpanel schließen',
    'chat.intentsPanel': 'Intentionen Panel',
    'chat.intents': 'Intentionen',
    'chat.closeIntentsPanel': 'Intentionen Panel schließen',
    'chat.intent': 'Absicht',
    'chat.searchQuery': 'Suchanfrage',
    'chat.searchResult': 'Suchergebnis',
    'chat.codeGenerated': 'Generierter Code',

    // Auth messages
    'auth.notConfiguredTitle': 'Authentifizierung nicht konfiguriert',
    'auth.notConfiguredSubtitle1':
      'Diese App hat keine konfigurierte Authentifizierung. Bitte fügen Sie einen Identitätsanbieter hinzu, indem Sie Ihre App im',
    'auth.azurePortal': 'Azure-Portal',
    'auth.notConfiguredSubtitle2': 'suchen und',
    'auth.instructions': 'diesen Anweisungen',
    'auth.notConfiguredSubtitle3': 'folgen.',
    'auth.configNote1': 'Die Konfiguration der Authentifizierung dauert einige Minuten.',
    'auth.configNote2':
      'Wenn Sie in den letzten 10 Minuten bereitgestellt haben, warten Sie bitte und laden Sie die Seite nach 10 Minuten neu.',

    'layout.logout': 'Abmelden',
    'layout.hideChatHistory': 'Chat-Verlauf verbergen',
    'layout.showChatHistory': 'Chat-Verlauf anzeigen',
    'layout.hideHistoryShort': 'Verlauf verbergen',
    'layout.showHistoryShort': 'Verlauf anzeigen',
    'layout.shareDialogTitle': 'Web-App teilen',
    'layout.copy': 'Kopieren',
    'layout.copied': 'Kopiert',

    // Answer component translations
    'answer.followupPrefix': 'Anschlussfragen:',
    'answer.followupHeading': 'Anschlussfragen',
    'answer.openReferences': 'Referenzen öffnen',
    'answer.multipleSources': '{count} Quellen',
    'answer.singleSource': '1 Quelle',
    'answer.disclaimer': 'AI-generierter Inhalt kann fehlerhaft sein',
    'answer.openIntents': 'Intentionen öffnen',
    'answer.showIntents': 'Intentionen anzeigen',

    // Feedback translations
    'feedback.likeLabel': 'Diese Antwort positiv bewerten',
    'feedback.dislikeLabel': 'Diese Antwort negativ bewerten',
    'feedback.sendFeedback': 'Feedback senden',
    'feedback.helpImprove': 'Ihr Feedback hilft uns, die Qualität der Antworten zu verbessern',
    'feedback.submitNotice': 'Durch Klicken auf „Senden“ wird Ihr Feedback an das verantwortliche Team übermittelt',
    'feedback.submit': 'Senden',
    'feedback.unhelpfulPrompt': 'Warum war diese Antwort nicht hilfreich?',
    'feedback.missingCitation': 'Zitate fehlen',
    'feedback.wrongCitation': 'Zitate sind unzutreffend',
    'feedback.outOfScope': 'Die Antwort basiert nicht auf meinen Daten',
    'feedback.inaccurateOrIrrelevant': 'Ungenau oder nicht relevant',
    'feedback.otherUnhelpful': 'Sonstiges',
    'feedback.reportInappropriate': 'Unangemessenen Inhalt melden',
    'feedback.contentIs': 'Der Inhalt ist',
    'feedback.hateSpeech': 'Hassreden, Stereotypisierung, Erniedrigung',
    'feedback.violent': 'Gewalttätig: Verherrlichung von Gewalt, Selbstverletzung',
    'feedback.sexual': 'Sexuell: explizite Inhalte, Grooming',
    'feedback.manipulative': 'Manipulativ: hinterhältig, emotional, aufdringlich, tyrannisch',
    'feedback.otherHarmful': 'Andere',

    'chatHistory.recent': 'Jüngste',
    'chatHistory.empty': 'Kein Chatverlauf.',
    'chatHistory.deleteDialog.title': 'Möchten Sie diesen Artikel wirklich löschen?',
    'chatHistory.deleteDialog.subText': 'Der Verlauf dieser Chatsitzung wird dauerhaft gelöscht.',
    'chatHistory.renameError.sameTitle': 'Fehler: Geben Sie einen neuen Titel ein, um fortzufahren.',
    'chatHistory.renameError.general': 'Fehler: Artikel konnte nicht umbenannt werden',
    'chatHistory.itemAriaLabel': 'Chatverlaufselement',
    'chatHistory.editFormAriaLabel': 'Titel bearbeiten Formular',
    'chatHistory.actionButtonsAriaLabel': 'Aktionsschaltflächen Gruppe',
    'chatHistory.confirmEditAriaLabel': 'Neuen Titel bestätigen',
    'chatHistory.cancelEditAriaLabel': 'Titelbearbeitung abbrechen',
    'chatHistory.deleteError': 'Fehler: Artikel konnte nicht gelöscht werden',
    'chatHistory.groupAriaLabel': 'Chatverlauf Gruppe',
    'chatHistory.listAriaLabel': 'Chatverlauf Liste',
    'chatHistory.loadingAriaLabel': 'weitere Chatverläufe werden geladen',
    close: 'Schließen',
    delete: 'Löschen',
    edit: 'Bearbeiten',
    cancel: 'Stornieren',
    'chatHistory.panelAriaLabel': 'Chatverlauf Panel',
    'chatHistory.headerAriaLabel': 'Chatverlauf Kopfzeile',
    'chatHistory.contentAriaLabel': 'Chatverlauf Panel Inhalt',
    'chatHistory.title': 'Chat-Verlauf',
    'chatHistory.clearAll': 'Gesamten Chatverlauf löschen',
    'chatHistory.clearAllDialog.title': 'Möchten Sie den gesamten Chatverlauf wirklich löschen?',
    'chatHistory.clearAllDialog.errorTitle': 'Fehler beim Löschen des gesamten Chatverlaufs',
    'chatHistory.clearAllDialog.subText': 'Der gesamte Chatverlauf wird dauerhaft gelöscht.',
    'chatHistory.clearAllDialog.errorSubText':
      'Bitte versuchen Sie es erneut. Wenn das Problem weiterhin besteht, wenden Sie sich bitte an den Site-Administrator.',
    'chatHistory.clearAllButton': 'Alles löschen',
    'chatHistory.loadingError': 'Fehler beim Laden des Chatverlaufs',
    'chatHistory.savingDisabled': 'Chatverlauf kann derzeit nicht gespeichert werden',
    'chatHistory.loading': 'Chatverlauf wird geladen',
    'chatHistory.loadingAriaLabel1': 'Chatverlauf wird geladen',
    hide: 'Verstecken'
  }
}
